org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
android.defaults.buildfeatures.buildconfig=true
android.overrideVersionCheck=true
android.newDsl=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
